//! The deterministic test target: the second column of the [QUAL-1]
//! qualification table and the scripted host its rows name.
//!
//! Some conditions the first slice's contracts fix cannot be produced on
//! demand through a real file or pipe: a close attempt that fails, a read that
//! stops short at a chosen call, a write the host accepts only in part. This
//! module qualifies the same program against a target whose file and
//! descriptor facilities are answered by one small scripted translation unit
//! linked into the compiled test artifact, so the forced condition is observed
//! through the same emitted lowering rather than through a model of it.
//!
//! It supplies exactly the arrangements those contract tests consume and
//! nothing else: it is not a simulator of the host and not an artifact-replay
//! framework. Adding an arrangement here is adding one scripted outcome to one
//! facility, and a facility exists here only once an operation's contract test
//! needs it.

use std::fmt::Write as _;
use std::process::Output;

use crate::backend::emitter::emit_llvm_for_target;
use crate::backend::qualification::SystemTarget;

use super::system::with_ir;
use super::{compile_link_and_run, host_optimized_module};

/// A host error the deterministic host can be scripted to report.
///
/// Each names the C macro the generated unit reports, so the value is the
/// selected host's own, never a number this module invents.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum HostError {
    /// An interrupted call. A close that reports it leaves the descriptor's
    /// state unknowable, which is exactly why [SYS-5] never retries after one.
    Interrupted,
}

impl HostError {
    const fn macro_name(self) -> &'static str {
        match self {
            Self::Interrupted => "EINTR",
        }
    }
}

/// One scripted outcome of one host call.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum HostOutcome {
    /// The call succeeds naturally.
    Succeed,
    /// The call fails and reports this error.
    Fail(HostError),
}

/// The scripted state one deterministic-host run answers from.
///
/// A script lists the outcome of each call to one facility in call order; a
/// call past the end of a list succeeds. That is the whole configuration
/// surface — no recorded session, no replay, and no per-test host code.
#[derive(Clone, Debug, Default)]
pub(super) struct HostScript {
    closes: Vec<HostOutcome>,
}

impl HostScript {
    pub(super) fn new() -> Self {
        Self::default()
    }

    /// Scripts the outcome of each close attempt, in call order.
    pub(super) fn closes(mut self, outcomes: &[HostOutcome]) -> Self {
        self.closes = outcomes.to_vec();
        self
    }

    /// Renders the host translation unit this script configures.
    fn unit(&self) -> String {
        let mut source = String::from(HOST_PRELUDE);
        source.push_str(&outcome_table("close", &self.closes));
        source.push_str(HOST_FACILITIES);
        source
    }
}

/// Renders one facility's scripted outcome table.
///
/// A `0` entry succeeds and a negative entry is the negated error the call
/// reports, which is how the facilities below read it back.
fn outcome_table(facility: &str, outcomes: &[HostOutcome]) -> String {
    let mut rendered = String::new();
    let mut entries = Vec::with_capacity(outcomes.len());
    for outcome in outcomes {
        entries.push(match outcome {
            HostOutcome::Succeed => "0".to_owned(),
            HostOutcome::Fail(error) => format!("-{}", error.macro_name()),
        });
    }
    // A zero-length array is not valid C, so an empty script keeps one unused
    // slot and a length of zero.
    let length = entries.len();
    if entries.is_empty() {
        entries.push("0".to_owned());
    }
    writeln!(
        rendered,
        "static const long wf_test_{facility}_script[] = {{ {} }};\n\
         static const unsigned long wf_test_{facility}_scripted = {length};\n\
         static unsigned long wf_test_{facility}_calls = 0;",
        entries.join(", ")
    )
    .expect("string writes do not fail");
    rendered
}

/// The fixed head of the generated host unit.
const HOST_PRELUDE: &str = "\
/* The deterministic test host for one Whitefoot backend test. Generated by\n\
   compiler/src/backend/tests/deterministic_target.rs; never checked in. */\n\
#include <errno.h>\n\
#include <stdarg.h>\n\
#include <stdio.h>\n\
#include <unistd.h>\n\
\n\
/* The descriptor the scripted directory open produces. It is deliberately\n\
   not a real open descriptor: nothing in the program may treat it as one. */\n\
#define WF_TEST_DIRECTORY 41\n\
\n\
";

/// The fixed body of the generated host unit: one function per facility a
/// [QUAL-1] deterministic-target row names.
const HOST_FACILITIES: &str = "\
\n\
/* Every facility appends one line to the real standard error so a test can\n\
   observe host-visible facts the source cannot see — how many attempts a\n\
   release made, and against which descriptor. */\n\
static void wf_test_trace(const char *line) {\n\
    unsigned long length = 0;\n\
    while (line[length] != '\\0') {\n\
        length++;\n\
    }\n\
    ssize_t written = write(2, line, length);\n\
    (void)written;\n\
}\n\
\n\
static long wf_test_step(const long *script, unsigned long scripted,\n\
                         unsigned long *calls) {\n\
    unsigned long call = *calls;\n\
    *calls = call + 1;\n\
    return call < scripted ? script[call] : 0;\n\
}\n\
\n\
int wf_test_open(const char *path, int flags, ...) {\n\
    char line[128];\n\
    (void)path;\n\
    (void)flags;\n\
    snprintf(line, sizeof line, \"wf_test open -> %d\\n\", WF_TEST_DIRECTORY);\n\
    wf_test_trace(line);\n\
    return WF_TEST_DIRECTORY;\n\
}\n\
\n\
int wf_test_close(int descriptor) {\n\
    char line[128];\n\
    long outcome = wf_test_step(wf_test_close_script, wf_test_close_scripted,\n\
                                &wf_test_close_calls);\n\
    snprintf(line, sizeof line, \"wf_test close fd=%d outcome=%ld\\n\", descriptor,\n\
             outcome);\n\
    wf_test_trace(line);\n\
    if (outcome < 0) {\n\
        errno = (int)(-outcome);\n\
        return -1;\n\
    }\n\
    return 0;\n\
}\n";

/// One run of one program against the deterministic test target.
pub(super) struct DeterministicRun {
    /// The compiled program's own result.
    pub(super) output: Output,
}

impl DeterministicRun {
    /// The host trace the scripted facilities produced.
    pub(super) fn trace(&self) -> String {
        String::from_utf8_lossy(&self.output.stderr).into_owned()
    }

    /// How many times one facility was reached.
    pub(super) fn attempts(&self, facility: &str) -> usize {
        let prefix = format!("wf_test {facility} ");
        self.trace()
            .lines()
            .filter(|line| line.starts_with(&prefix))
            .count()
    }
}

/// Emits one source against the deterministic test target.
pub(super) fn emit_for_deterministic_target(source: &[u8]) -> String {
    with_ir(source, |program| {
        emit_llvm_for_target(program, SystemTarget::deterministic_test())
            .expect("the deterministic test target admits the program")
            .into_string()
    })
}

/// Compiles one source against the deterministic test target, links it with
/// the unit the script configures, and runs it.
pub(super) fn run_on_deterministic_host(
    source: &[u8],
    script: &HostScript,
    arguments: &[&[u8]],
) -> DeterministicRun {
    let llvm = emit_for_deterministic_target(source);
    let output = compile_link_and_run(&llvm, Some(&script.unit()), arguments);
    DeterministicRun { output }
}

/// A command that binds the initial working directory and returns a fixed
/// status, so its only host activity is the [SYS-5] release of one
/// `DirectoryRead`.
const RELEASES_ONE_DIRECTORY: &[u8] =
    br#"command fn main(command.cwd as cwd: own DirectoryRead) -> own ExitStatus external, blocks {
  return exit_status(code: 0_u8);
}
"#;

#[test]
fn the_deterministic_target_qualifies_the_same_program_as_the_native_target() {
    // The second column is a different implementation of the same
    // specification, not a relaxed one: it qualifies exactly the facilities
    // the native target qualifies, with the same [QUAL-2] guarantees.
    with_ir(RELEASES_ONE_DIRECTORY, |program| {
        let native = SystemTarget::for_triple(
            crate::backend::target::TargetLayout::host()
                .expect("a supported host")
                .triple(),
        )
        .expect("the host triple is a qualified target");
        let deterministic = SystemTarget::deterministic_test();
        assert_eq!(
            crate::backend::qualification::qualify_program(native, program)
                .expect("the native target admits the program")
                .kind(),
            crate::backend::qualification::qualify_program(deterministic, program)
                .expect("the deterministic target admits the program")
                .kind()
        );
    });
}

#[test]
fn only_the_host_facing_rows_differ_between_the_two_targets() {
    // Selecting the deterministic target redirects exactly the rows that
    // reach a real operating-system object. Everything else — the wrappers,
    // the bootstrap, the release shape, the emitted call count — is the same
    // code under test.
    let native = super::compile(RELEASES_ONE_DIRECTORY);
    let deterministic = emit_for_deterministic_target(RELEASES_ONE_DIRECTORY);

    assert!(native.contains("declare i32 @close(i32)"));
    assert!(native.contains("declare i32 @open(ptr, i32, ...)"));
    assert!(!native.contains("wf_test"));

    assert!(deterministic.contains("declare i32 @wf_test_close(i32)"));
    assert!(deterministic.contains("declare i32 @wf_test_open(ptr, i32, ...)"));
    // The redirect is complete: no use site keeps calling the native facility.
    assert!(!deterministic.contains("@close(i32 "));
    assert!(!deterministic.contains("@open(ptr "));

    // One release, one close attempt, on either target [SYS-5].
    assert_eq!(native.matches("call i32 @close(i32").count(), 1);
    assert_eq!(
        deterministic.matches("call i32 @wf_test_close(i32").count(),
        1
    );

    // The rest of the module is identical, so a condition forced on the
    // deterministic host is forced on the same lowering the native target
    // emits.
    assert_eq!(
        native
            .replace("@close", "@wf_test_close")
            .replace("@open", "@wf_test_open"),
        deterministic
    );
}

#[test]
fn a_release_close_that_fails_is_attempted_once_and_never_retried() {
    // [SYS-5]: a consuming close is one attempt whose diagnostic is
    // discarded. An interrupted close leaves the descriptor's state
    // unknowable, so retrying could close a descriptor the host has already
    // reused; the release must not. A real directory close cannot be made to
    // report `EINTR` on demand, which is why this case is the deterministic
    // target's.
    let run = run_on_deterministic_host(
        RELEASES_ONE_DIRECTORY,
        &HostScript::new().closes(&[HostOutcome::Fail(HostError::Interrupted)]),
        &[],
    );

    assert_eq!(
        run.attempts("close"),
        1,
        "an interrupted close is never retried; trace was {:?}",
        run.trace()
    );
    assert!(run.trace().contains("wf_test close fd=41 outcome=-4"));
    // The failed release changes nothing the source can observe: the command
    // still produces its own status.
    assert_eq!(run.output.status.code(), Some(0));
}

#[test]
fn a_release_close_that_succeeds_is_also_exactly_one_attempt() {
    // The control for the case above: the single attempt is a property of the
    // release, not of the failure.
    let run = run_on_deterministic_host(
        RELEASES_ONE_DIRECTORY,
        &HostScript::new().closes(&[HostOutcome::Succeed]),
        &[],
    );

    assert_eq!(run.attempts("close"), 1);
    assert!(run.trace().contains("wf_test close fd=41 outcome=0"));
    assert_eq!(run.output.status.code(), Some(0));
}

#[test]
fn the_deterministic_release_keeps_the_native_optimized_shape() {
    // [QUAL-3]: the wrapper inlines and the release stays one direct call on
    // the selected target's own facility, with no dispatch table, no handle
    // lookup, and no allocation introduced by the second column.
    let optimized = host_optimized_module(&emit_for_deterministic_target(RELEASES_ONE_DIRECTORY));
    assert_eq!(optimized.matches("@wf_test_close(").count(), 2);
    assert!(!optimized.contains("@malloc"));
}
