//! Conservative textual LLVM emission for the active Whitefoot specification.

mod emitter;
mod qualification;
mod stack_ledger;
mod target;

#[cfg(test)]
mod tests;

pub use emitter::{
    BackendFailure, COMPLETION_BRIDGE_HEADER, COMPLETION_BRIDGE_SOURCE, COMPLETION_CONTRACT_HEADER,
    COMPLETION_FILE_ADAPTER_HEADER, COMPLETION_FILE_ADAPTER_SOURCE,
    COMPLETION_LINUX_IO_URING_HEADER, COMPLETION_LINUX_IO_URING_SOURCE, COMPLETION_RUNTIME_SOURCE,
    COMPLETION_WINDOWS_BLOCKING_HEADER, COMPLETION_WINDOWS_BLOCKING_SOURCE,
    COMPLETION_WINDOWS_BRIDGE_SOURCE, COMPLETION_WINDOWS_HEADER, COMPLETION_WINDOWS_IOCP_HEADER,
    COMPLETION_WINDOWS_IOCP_SOURCE, COMPLETION_WINDOWS_NATIVE_API_HEADER,
    COMPLETION_WINDOWS_SOURCE, FLOOR_RUNTIME_SOURCE, FLOOR_STACK_BYTES,
    FLOOR_WINDOWS_RUNTIME_SOURCE, PARALLEL_WINDOWS_RUNTIME_SOURCE, SCHED_CORE_HEADER,
    SCHED_CORE_SOURCE, SCHED_ENTRY_HEADER, SCHED_ENTRY_SOURCE, SCHED_PRIM_HEADER,
    SCHED_PRIM_HOST_SOURCE, SCHED_SWITCH_HEADER, WINDOWS_RUNTIME_HEADER, WINDOWS_RUNTIME_SOURCE,
    WRITER_SCHEDULER_WINDOWS_SOURCE, emit_llvm, module_requires_completion_runtime,
    module_requires_parallel_runtime,
};
pub use stack_ledger::{Architecture, stack_ledger};
