// Generated by `whitefoot-spec --emit-identity`; never edit by hand.
// Regenerate: cargo run --bin whitefoot-spec -- --emit-identity src/spec_identity.rs
// Freshness is machine-checked: `whitefoot-spec --check-identity <path>` and
// the test `committed_identity_is_fresh` in `src/bin/spec.rs` byte-compare
// this file against a fresh generation.

//! Machine-derived identity of the embedded active specification and its
//! `governance/APPROVALS.md` activation chain. Each value is computed from
//! those embedded bytes at generation time, so no activation hand-bumps a
//! scalar here or at a consumer.

/// Version token on the embedded specification's title line.
pub const SPEC_VERSION: &str = "v0.45";

/// Lowercase SHA-256 hex of the embedded specification bytes.
pub const SPEC_SHA256_HEX: &str =
    "ddebbc4a7fc39034fc01f6eb5e9e075967a011a4241aa691cc87a5252d71c2bb";

/// Number of `ACTIVE-SPEC:` records in the embedded activation chain.
pub const ACTIVATION_CHAIN_LENGTH: usize = 37;

/// Number of bracketed rule definitions in the embedded specification.
pub const RULE_COUNT: usize = 148;
