#!/usr/bin/env python3
"""Build the machine-readable G0 coverage-cluster policy registry."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CENSUS = ROOT / "RUST-DATA-CONTRACT-CENSUS.tsv"
MATRIX = ROOT / "DERIVATION-MATRIX.tsv"
OUTPUT = ROOT / "G0-COVERAGE-CLUSTER-REGISTRY.tsv"

FIELDS = [
    "cluster_ordinal",
    "cluster_id",
    "family",
    "semantic_class",
    "importability",
    "refinement_policy",
    "evidence_universe_policy",
    "allowed_evidence_dispositions",
    "prohibited_direct_uses",
    "census_row_sha256",
    "derivation_row_sha256",
    "policy_version",
]

SEMANTIC_CLASS = "G0_COVERAGE_CLUSTER"
IMPORTABILITY = "NON_IMPORTABLE"
REFINEMENT_POLICY = "FAMILY_LOCK_COMPLETE_EVIDENCE_TO_MEMBER_OUTCOME"
EVIDENCE_UNIVERSE_POLICY = "ALL_SAFE_D10_UNSAFE_IMPL_AND_HELPER_KEYS"
ALLOWED_EVIDENCE_DISPOSITIONS = (
    "REFINED_IN_LOCK;PREDECESSOR_PROVED;EXCLUDED_BLOCKS_CLAIM"
)
PROHIBITED_DIRECT_USES = (
    "FAMILY_CLOSURE_UNIT;MEMBER_CONTRACT;OUTCOME_CONTRACT;"
    "CAPABILITY_INHERITANCE;COST_INHERITANCE;FAMILY_LOCK_IMPORT;"
    "CANDIDATE_CONSTRUCTION;SCORED_EXPERIMENT;FAMILY_E;FAMILY_P"
)
POLICY_VERSION = "xlang-g0-coverage-cluster-policy-v1"


def fail(message: str) -> None:
    raise SystemExit(f"G0 coverage-cluster registry build failed: {message}")


def read_tsv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        fields = list(reader.fieldnames or [])
        rows = list(reader)
    if not fields or "contract_id" not in fields:
        fail(f"{path.name} has no contract_id column")
    if any(None in row for row in rows):
        fail(f"{path.name} has extra TSV columns")
    if any(any("\r" in value or "\n" in value for value in row.values()) for row in rows):
        fail(f"{path.name} has an embedded newline")
    return fields, rows


def row_sha256(fields: list[str], row: dict[str, str]) -> str:
    encoded = ("\t".join(row[field] for field in fields) + "\n").encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def build_rows() -> list[dict[str, str]]:
    census_fields, census_rows = read_tsv(CENSUS)
    matrix_fields, matrix_rows = read_tsv(MATRIX)
    census_ids = [row["contract_id"] for row in census_rows]
    matrix_ids = [row["contract_id"] for row in matrix_rows]
    if len(census_ids) != 276:
        fail(f"census has {len(census_ids)} rows, expected 276")
    if len(set(census_ids)) != len(census_ids):
        fail("census cluster IDs are not unique")
    if matrix_ids != census_ids:
        fail("census and derivation-matrix cluster order differ")

    rows = []
    for ordinal, (census_row, matrix_row) in enumerate(
        zip(census_rows, matrix_rows), start=1
    ):
        rows.append(
            {
                "cluster_ordinal": str(ordinal),
                "cluster_id": census_row["contract_id"],
                "family": census_row["family"],
                "semantic_class": SEMANTIC_CLASS,
                "importability": IMPORTABILITY,
                "refinement_policy": REFINEMENT_POLICY,
                "evidence_universe_policy": EVIDENCE_UNIVERSE_POLICY,
                "allowed_evidence_dispositions": ALLOWED_EVIDENCE_DISPOSITIONS,
                "prohibited_direct_uses": PROHIBITED_DIRECT_USES,
                "census_row_sha256": row_sha256(census_fields, census_row),
                "derivation_row_sha256": row_sha256(matrix_fields, matrix_row),
                "policy_version": POLICY_VERSION,
            }
        )
    return rows


def render(rows: list[dict[str, str]]) -> str:
    output = io.StringIO(newline="")
    writer = csv.DictWriter(
        output,
        fieldnames=FIELDS,
        delimiter="\t",
        lineterminator="\n",
    )
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the checked-in registry exactly matches generated bytes",
    )
    arguments = parser.parse_args()
    expected = render(build_rows())
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            fail(f"{OUTPUT.name} is missing or stale")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")
    print(
        "G0 coverage-cluster registry: PASS — 276 ordered non-importable "
        "coverage clusters carry the canonical refinement policy"
    )


if __name__ == "__main__":
    main()
