//! Derives the active specification's identity and grammar tables at build time.
//!
//! The identity used to be a generated module committed beside the source,
//! with a test proving the committed copy matched a fresh generation. That is
//! a second copy of a fact the crate already embeds, and the test existed only
//! to police the copy: an amendment that forgot to regenerate turned the gate
//! red rather than the build. Computing it here removes the copy, the
//! regeneration step, and the test together.
//!
//! Only the two values that must exist in constant position are emitted. The
//! rule count is scanned live from the embedded text where it is used, because
//! nothing needs it before runtime and a second scanner here would reintroduce
//! exactly the duplication this removes.

use std::{env, fs, path::Path};

#[path = "src/syntax/grammar/generator.rs"]
mod grammar_generator;

mod sha256 {
    include!("src/spec/sha256.rs");
}

const SPEC: &str = "../spec/kernel-spec.md";
const TITLE: &str = "# Kernel Specification ";

fn main() {
    println!("cargo::rerun-if-changed={SPEC}");
    println!("cargo::rerun-if-changed=src/spec/sha256.rs");
    println!("cargo::rerun-if-changed=src/syntax/grammar/generator.rs");
    println!("cargo::rerun-if-changed=src/syntax/grammar/generator/ebnf.rs");
    println!("cargo::rerun-if-changed=src/syntax/grammar/generator/model.rs");

    let bytes = fs::read(SPEC).unwrap_or_else(|error| panic!("read {SPEC}: {error}"));
    let text = std::str::from_utf8(&bytes).expect("the specification is UTF-8");
    let version = text
        .lines()
        .next()
        .and_then(|line| line.strip_prefix(TITLE))
        .unwrap_or_else(|| panic!("{SPEC} has no `{TITLE}vN` title line"));

    let mut hex = String::with_capacity(64);
    for byte in sha256::digest(&bytes) {
        hex.push_str(&format!("{byte:02x}"));
    }

    let module = format!(
        r#"// Generated by build.rs from the specification's own bytes; not committed.

/// Version token on the embedded specification's title line.
pub const SPEC_VERSION: &str = "{version}";

/// Lowercase SHA-256 hex of the embedded specification bytes.
///
/// Decoded rather than recomputed by consumers: a constant is re-evaluated in
/// every crate that reads it, and hashing the whole specification in the
/// constant evaluator costs seconds per crate. Cargo regenerates this module
/// whenever the active specification changes.
pub const SPEC_SHA256_HEX: &str = "{hex}";
"#
    );

    let out = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("spec_identity.rs");
    fs::write(&out, module).unwrap_or_else(|error| panic!("write {}: {error}", out.display()));

    let tables = grammar_generator::generate("spec/kernel-spec.md", text);
    let out = out.with_file_name("grammar_tables.rs");
    fs::write(&out, tables).unwrap_or_else(|error| panic!("write {}: {error}", out.display()));
}
