[package]
name = "whitefoot"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
doctest = false

[[bin]]
name = "whitefoot-spec"
path = "src/bin/spec.rs"

[[bin]]
name = "whitefoot-grammar"
path = "src/bin/grammar.rs"

[[bin]]
name = "whitefoot-grammar-tables"
path = "src/bin/grammar_tables/main.rs"

[[bin]]
name = "whitefootc"
path = "src/bin/whitefootc.rs"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
