//! Explicit investigation-only reuse of the compiler's grammar generator.
//! Run from the repository root; no ordinary gate depends on this file.
use std::{fs, path::PathBuf, process::Command};

fn replace_once(text: &mut String, from: &str, to: &str) {
    assert_eq!(
        text.matches(from).count(),
        1,
        "qualification adapter drift: {from}"
    );
    *text = text.replacen(from, to, 1);
}

fn main() {
    let repo = std::env::current_dir().expect("repository directory");
    let home = repo.join("research/investigations/modular-compilation");
    let syntax = fs::read_to_string(home.join("SYNTAX.md")).expect("candidate grammar");
    let names: Vec<_> = syntax
        .lines()
        .filter_map(|line| {
            line.split_once(" := ")
                .map(|(name, _)| name.trim().to_owned())
        })
        .collect();
    let scratch: PathBuf =
        std::env::temp_dir().join(format!("wf-module-grammar-{}", std::process::id()));
    fs::create_dir(&scratch).expect("unique temporary directory");
    fs::create_dir(scratch.join("generator")).unwrap();
    let base = repo.join("compiler/src/syntax/grammar");
    let mut generator = fs::read_to_string(base.join("generator.rs")).unwrap();
    let start = generator.find("const ENUM_ORDER:").unwrap();
    let end = start + generator[start..].find("\n];").unwrap() + 3;
    let inventory = format!(
        "const ENUM_ORDER: &[&str] = &[{}];",
        names
            .iter()
            .map(|n| format!("{n:?}"))
            .collect::<Vec<_>>()
            .join(",")
    );
    generator.replace_range(start..end, &inventory);
    fs::write(scratch.join("generator.rs"), generator).unwrap();
    let mut ebnf = fs::read_to_string(base.join("generator/ebnf.rs")).unwrap();
    replace_once(
        &mut ebnf,
        "        86,",
        &format!("        {},", names.len()),
    );
    fs::write(scratch.join("generator/ebnf.rs"), ebnf).unwrap();
    let mut model = fs::read_to_string(base.join("generator/model.rs")).unwrap();
    let additions = [
        "public",
        "alias",
        "pkg",
        "target",
        "observe",
        "footprint",
        "view",
    ]
    .map(|name| {
        let mut chars = name.chars();
        let variant = chars.next().unwrap().to_uppercase().to_string() + chars.as_str();
        format!("        ({name:?}, {variant:?}),\n")
    })
    .concat();
    replace_once(
        &mut model,
        "    const TABLE: &[(&str, &str)] = &[\n",
        &("    const TABLE: &[(&str, &str)] = &[\n".to_owned() + &additions),
    );
    fs::write(scratch.join("generator/model.rs"), model).unwrap();
    fs::write(scratch.join("main.rs"), r#"
#[path = "generator.rs"] mod generator;
fn main() {
    let path = std::env::args().nth(1).unwrap();
    let syntax = std::fs::read_to_string(&path).unwrap();
    for (name, text) in [("source", syntax.clone()), ("graph", syntax.replace("program := alias_decl* item*", "program := graph_file"))] {
        let generated = generator::generate(&path, &text);
        println!("{name}: strong LL(2) and overlapping-token-predicate checks passed ({} generated bytes)", generated.len());
    }
    let broken = syntax.replace("expr := operand infix_tail?", "expr := atom infix_tail? | call");
    assert_ne!(broken, syntax);
    std::panic::set_hook(Box::new(|_| {}));
    let failure = std::panic::catch_unwind(|| generator::generate(&path, &broken)).expect_err("the unfactored qualified-name control must fail");
    let message = failure.downcast_ref::<String>().map(String::as_str).or_else(|| failure.downcast_ref::<&str>().copied()).expect("grammar conflict message");
    assert!(message.contains("[GRAM-1]") && message.contains("two-token word"), "control failed for an unrelated reason: {message}");
    println!("negative control: unfactored qualified call/value alternatives rejected");
}
"#).unwrap();
    let compile = Command::new("rustc")
        .args(["--edition=2024", "-Awarnings"])
        .arg(scratch.join("main.rs"))
        .arg("-o")
        .arg(scratch.join("probe"))
        .status()
        .unwrap();
    let success = compile.success()
        && Command::new(scratch.join("probe"))
            .arg(home.join("SYNTAX.md"))
            .status()
            .unwrap()
            .success();
    fs::remove_dir_all(&scratch).unwrap();
    assert!(success, "candidate grammar qualification failed");
    println!(
        "{} candidate productions; no compiler or specification files modified",
        names.len()
    );
}
