//! Explicit investigation-only reuse of the compiler's grammar generator.
//! Run from the repository root; no ordinary gate depends on this file.
use std::{fs, process::Command};

fn replace_once(text: &mut String, from: &str, to: &str) {
    assert_eq!(
        text.matches(from).count(),
        1,
        "qualification adapter drift: {from}"
    );
    *text = text.replacen(from, to, 1);
}

/// Production names in fenced `wf-ebnf` blocks, in definition order.
fn production_names(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut fenced = false;
    for line in text.lines() {
        if line.starts_with("```wf-ebnf") {
            fenced = true;
        } else if line.starts_with("```") {
            fenced = false;
        } else if fenced {
            if let Some((name, _)) = line.split_once(" := ") {
                names.push(name.trim().to_owned());
            }
        }
    }
    names
}

const PROBE: &str = r#"
#[path = "generator.rs"] mod generator;
use generator::{ebnf, model};
use std::collections::{BTreeMap, BTreeSet};

type Prefixes = BTreeMap<String, BTreeSet<Vec<model::Pred>>>;

fn prefixes(text: &str) -> Prefixes {
    let raw = ebnf::productions(text);
    let names: Vec<String> = raw.iter().map(|entry| entry.name.clone()).collect();
    let (trees, index) = ebnf::parse_all(&raw);
    let grammar = model::Grammar::build(&trees, &names, &index);
    let first = model::first_sets(&grammar);
    names
        .iter()
        .enumerate()
        .map(|(production, name)| {
            let words = first.node[grammar.roots[production]]
                .iter()
                .map(|word| word.iter().map(|token| token.pred).collect())
                .collect();
            (name.clone(), words)
        })
        .collect()
}

fn lost(active: &Prefixes, candidate: &Prefixes) -> Vec<String> {
    let mut problems = Vec::new();
    for (name, words) in active {
        match candidate.get(name) {
            None => problems.push(format!("{name}: production removed")),
            Some(kept) => {
                for word in words.difference(kept) {
                    problems.push(format!("{name}: lost prefix {word:?}"));
                }
            }
        }
    }
    problems
}

fn main() {
    let arguments: Vec<String> = std::env::args().collect();
    let syntax_path = &arguments[1];
    let syntax = std::fs::read_to_string(syntax_path).unwrap();
    let specification = std::fs::read_to_string(&arguments[2]).unwrap();
    let graph = syntax.replace("program := alias_decl* item*", "program := graph_file");
    assert_ne!(graph, syntax);
    for (name, text) in [("source", &syntax), ("graph", &graph)] {
        let generated = generator::generate(syntax_path, text);
        println!("{name}: strong LL(2) and overlapping-token-predicate checks passed ({} generated bytes)", generated.len());
    }
    let active = prefixes(&specification);
    let problems = lost(&active, &prefixes(&syntax));
    assert!(problems.is_empty(), "the candidate drops active forms:\n{}", problems.join("\n"));
    println!("coverage: all {} active productions keep their two-token prefixes", active.len());

    let unfactored = syntax.replace("expr := operand infix_tail?", "expr := atom infix_tail? | call");
    assert_ne!(unfactored, syntax);
    std::panic::set_hook(Box::new(|_| {}));
    let failure = std::panic::catch_unwind(|| generator::generate(syntax_path, &unfactored))
        .expect_err("the unfactored qualified-name control must fail");
    let _ = std::panic::take_hook();
    let message = failure
        .downcast_ref::<String>()
        .map(String::as_str)
        .or_else(|| failure.downcast_ref::<&str>().copied())
        .expect("grammar conflict message");
    assert!(message.contains("[GRAM-1]") && message.contains("two-token word"), "control failed for an unrelated reason: {message}");
    println!("negative control: unfactored qualified call/value alternatives rejected");

    let narrowed = syntax.replace("affine_factor := operand | \"(\" affine_expr \")\"", "affine_factor := atom | \"(\" affine_expr \")\"");
    assert_ne!(narrowed, syntax);
    let dropped = lost(&active, &prefixes(&narrowed));
    assert!(dropped.iter().any(|problem| problem.starts_with("affine_factor:")), "the narrowed affine_factor control must lose active prefixes");
    println!("negative control: narrowed affine_factor loses {} active prefixes", dropped.len());
}
"#;

fn main() {
    let repo = std::env::current_dir().expect("repository directory");
    let home = repo.join("research/investigations/modular-compilation");
    let syntax = fs::read_to_string(home.join("SYNTAX.md")).expect("candidate grammar");
    let names = production_names(&syntax);
    let scratch = std::env::temp_dir().join(format!("wf-module-grammar-{}", std::process::id()));
    fs::create_dir(&scratch).expect("unique temporary directory");
    fs::create_dir(scratch.join("generator")).unwrap();
    let base = repo.join("compiler/src/syntax/grammar");
    let mut generator = fs::read_to_string(base.join("generator.rs")).unwrap();
    let start = generator.find("const ENUM_ORDER:").unwrap();
    let end = start + generator[start..].find("\n];").unwrap() + 3;
    let inventory = format!(
        "const ENUM_ORDER: &[&str] = &[{}];",
        names
            .iter()
            .map(|n| format!("{n:?}"))
            .collect::<Vec<_>>()
            .join(",")
    );
    generator.replace_range(start..end, &inventory);
    replace_once(&mut generator, "mod ebnf;", "pub mod ebnf;");
    replace_once(&mut generator, "mod model;", "pub mod model;");
    fs::write(scratch.join("generator.rs"), generator).unwrap();
    // The probe reads both the candidate and the active inventory, whose
    // sizes differ; the candidate count is checked below instead.
    let mut ebnf = fs::read_to_string(base.join("generator/ebnf.rs")).unwrap();
    replace_once(&mut ebnf, "        85,", "        out.len(),");
    fs::write(scratch.join("generator/ebnf.rs"), ebnf).unwrap();
    let mut model = fs::read_to_string(base.join("generator/model.rs")).unwrap();
    let additions = ["public", "alias", "pkg"]
        .map(|name| {
            let mut chars = name.chars();
            let variant = chars.next().unwrap().to_uppercase().to_string() + chars.as_str();
            format!("        ({name:?}, {variant:?}),\n")
        })
        .concat();
    replace_once(
        &mut model,
        "    const TABLE: &[(&str, &str)] = &[\n",
        &("    const TABLE: &[(&str, &str)] = &[\n".to_owned() + &additions),
    );
    fs::write(scratch.join("generator/model.rs"), model).unwrap();
    fs::write(scratch.join("main.rs"), PROBE).unwrap();
    let compile = Command::new("rustc")
        .args(["--edition=2024", "-Awarnings"])
        .arg(scratch.join("main.rs"))
        .arg("-o")
        .arg(scratch.join("probe"))
        .status()
        .unwrap();
    let success = compile.success()
        && Command::new(scratch.join("probe"))
            .arg(home.join("SYNTAX.md"))
            .arg(repo.join("spec/kernel-spec.md"))
            .status()
            .unwrap()
            .success();
    fs::remove_dir_all(&scratch).unwrap();
    assert!(success, "candidate grammar qualification failed");
    println!(
        "{} candidate productions; no compiler or specification files modified",
        names.len()
    );
}
